const menu = [
  {
  id: 1,
  title: 'Panqueques',
  category: 'desayuno',
  price: 15.99,
  img: '/images/item-1.jpeg',
  desc: 'Panqueques esponjosos con miel de maple y frutas frescas. Perfectos para comenzar el día con energía y disfrutar de un desayuno delicioso y nutritivo.',
  },
  {
  id: 2,
  title: 'Doble de comedor',
  category: 'almuerzo',
  price: 13.99,
  img: '/images/item-2.jpeg',
  desc: 'Una jugosa hamburguesa doble con queso, acompañada de papas fritas y ensalada. Ideal para disfrutar de un almuerzo completo y sabroso.',
  },
  {
  id: 3,
  title: 'Batido Godzilla',
  category: 'batidos',
  price: 6.99,
  img: '/images/item-3.jpeg',
  desc: 'Un delicioso batido de chocolate con trozos de galleta Oreo, crema batida y sirope de chocolate. Perfecto para refrescarte y satisfacer tus antojos dulces.',
  },
  {
  id: 4,
  title: 'Encanto campestre',
  category: 'desayuno',
  price: 20.99,
  img: '/images/item-4.jpeg',
  desc: 'Un desayuno completo con huevos revueltos, tocino, salchichas, tomates asados y tostadas. Un clásico para disfrutar de una mañana llena de sabor.',
  },
  {
  id: 5,
  title: 'Ataque de huevo',
  category: 'almuerzo',
  price: 22.99,
  img: '/images/item-5.jpeg',
  desc: 'Un nutritivo plato con huevo a la plancha, aguacate, espinacas y quinoa. Ideal para un almuerzo saludable y delicioso.',
  },
  {
  id: 6,
  title: 'Sueño de Oreo',
  category: 'batidos',
  price: 18.99,
  img: '/images/item-6.jpeg',
  desc: 'Un cremoso batido de vainilla con trozos de galleta Oreo, nata montada y sirope de caramelo. Una opción irresistible para los amantes del dulce.',
  },
  {
  id: 7,
  title: 'Exceso de bacon',
  category: 'desayuno',
  price: 8.99,
  img: '/images/item-7.jpeg',
  desc: 'Huevos revueltos con tiras de bacon crujiente, acompañados de tostadas y salsa de tomate. Un desayuno para disfrutar de los sabores clásicos y llenarte de energía.',
  },
  {
  id: 8,
  title: 'Clásico americano',
  category: 'almuerzo',
  price: 12.99,
  img: '/images/item-8.jpeg',
  desc: 'Un sándwich de pollo a la parrilla con lechuga, tomate, cebolla y mayonesa, acompañado de una porción de papas fritas. Un almuerzo delicioso y lleno de sabor.',
  },
  {
    id: 9,
    title: 'Compañero de cuarentena',
    category: 'batidos',
    price: 16.99,
    img: '/images/item-9.jpeg',
    desc: `Un refrescante batido de frutas tropicales con mango, piña, fresas y banano, mezclado con yogur natural. Perfecto para disfrutar de un momento de frescura y sabor.`,
  },

];
export default menu;
